export const RETRIEVE_PRODUCTS_SUCCESS = 'RETRIEVE_PRODUCTS_SUCCESS'
export const RETRIEVE_PRODUCTS_FAILURE = 'RETRIEVE_PRODUCTS_FAILURE'
export const RETRIEVE_PRODUCTS_REQUEST ='RETRIEVE_PRODUCTS_REQUEST'

export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS'
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE'
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS'
export const EDIT_PRODUCT_FAILURE = 'EDIT_PRODUCT_FAILURE'
export const DELETE_PRODUCT_SUCCESS ='DELETE_PRODUCT_SUCCESS'
export const DELETE_PRODUCT_FAILURE ='DELETE_PRODUCT_FAILURE'

export const RETRIEVE_CLIENTS_SUCCESS = 'RETRIEVE_CLIENTS_SUCCESS'
export const RETRIEVE_CLIENTS_FAILURE = 'RETRIEVE_CLIENTS_FAILURE'
export const CREATE_CLIENTS_SUCCESS = 'CREATE_CLIENTS_SUCCESS'
export const CREATE_CLIENTS_FAILURE = 'CREATE_CLIENTS_FAILURE'
export const EDIT_CLIENTS_SUCCESS = 'EDIT_CLIENTS_SUCCESS'
export const EDIT_CLIENTS_FAILURE = 'EDIT_CLIENTS_FAILURE'
export const DELETE_CLIENTS_SUCCESS ='DELETE_CLIENTS_SUCCESS'
export const DELETE_CLIENTS_FAILURE ='DELETE_CLIENTS_FAILURE'

export const RETRIEVE_DEALERS_SUCCESS = 'RETRIEVE_DEALERS_SUCCESS'
export const RETRIEVE_DEALERS_FAILURE = 'RETRIEVE_DEALERS_FAILURE'
export const CREATE_DEALER_SUCCESS = 'CREATE_DEALER_SUCCESS'
export const CREATE_DEALER_FAILURE = 'CREATE_DEALER_FAILURE'
export const EDIT_DEALER_SUCCESS = 'EDIT_DEALER_SUCCESS'
export const EDIT_DEALER_FAILURE = 'EDIT_DEALER_FAILURE'
export const DELETE_DEALER_SUCCESS ='DELETE_DEALER_SUCCESS'
export const DELETE_DEALER_FAILURE ='DELETE_DEALER_FAILURE'

export const RETRIEVE_STOCKS_SUCCESS = 'RETRIEVE_STOCKS_SUCCESS'
export const RETRIEVE_STOCKS_FAILURE = 'RETRIEVE_STOCKS_FAILURE'
export const RETRIEVE_STOCKS_REQUEST ='RETRIEVE_STOCKS_REQUEST'
export const RETRIEVE_STOCK_BY_BARCODE_SUCCESS = 'RETRIEVE_STOCK_BY_BARCODE_SUCCESS'
export const RETRIEVE_STOCK_BY_BARCODE_FAILURE = 'RETRIEVE_STOCK_BY_BARCODE_FAILURE'
export const RETRIEVE_STOCK_BY_BARCODE_REQUEST = 'RETRIEVE_STOCK_BY_BARCODE_REQUEST'

export const CREATE_STOCKS_SUCCESS = 'CREATE_STOCKS_SUCCESS'
export const CREATE_STOCKS_FAILURE = 'CREATE_STOCKS_FAILURE'
export const EDIT_STOCKS_SUCCESS = 'EDIT_STOCKS_SUCCESS'
export const EDIT_STOCKS_FAILURE = 'EDIT_STOCKS_FAILURE'
export const DELETE_STOCKS_SUCCESS ='DELETE_STOCKS_SUCCESS'
export const DELETE_STOCKS_FAILURE ='DELETE_STOCKS_FAILURE'

export const RETRIEVE_PRODUCT_FAILURE ='RETRIEVE_PRODUCT_FAILURE'
export const RETRIEVE_PRODUCT_SUCCESS ='RETRIEVE_PRODUCT_SUCCESS'
export const RETRIEVE_PRODUCT_REQUEST ='RETRIEVE_PRODUCT_REQUEST'

export const RETRIEVE_RECEIVINGS_SUCCESS = 'RETRIEVE_RECEIVINGS_SUCCESS'
export const RETRIEVE_RECEIVINGS_FAILURE = 'RETRIEVE_RECEIVINGS_FAILURE'
export const CREATE_RECEIVING_SUCCESS = 'CREATE_RECEIVING_SUCCESS'
export const CREATE_RECEIVING_FAILURE = 'CREATE_RECEIVING_FAILURE'
export const EDIT_RECEIVING_SUCCESS = 'EDIT_RECEIVING_SUCCESS'
export const EDIT_RECEIVING_FAILURE = 'EDIT_RECEIVING_FAILURE'
export const DELETE_RECEIVING_SUCCESS ='DELETE_RECEIVING_SUCCESS'
export const DELETE_RECEIVING_FAILURE ='DELETE_RECEIVING_FAILURE'
export const SET_RECEIVING_STATUS_SUCCESS = 'SET_RECEIVING_STATUS_SUCCESS'
export const SET_RECEIVING_STATUS_FAILURE = 'SET_RECEIVING_STATUS_FAILURE'

export const RETRIEVE_PAYMENTS_SUCCESS = 'RETRIEVE_PAYMENTS_SUCCESS'
export const RETRIEVE_PAYMENTS_FAILURE = 'RETRIEVE_PAYMENTS_FAILURE'
export const CREATE_PAYMENT_SUCCESS = 'CREATE_PAYMENT_SUCCESS'
export const CREATE_PAYMENT_FAILURE = 'CREATE_PAYMENT_FAILURE'
export const EDIT_PAYMENT_SUCCESS = 'EDIT_PAYMENT_SUCCESS'
export const EDIT_PAYMENT_FAILURE = 'EDIT_PAYMENT_FAILURE'
export const DELETE_PAYMENT_SUCCESS ='DELETE_PAYMENT_SUCCESS'
export const DELETE_PAYMENT_FAILURE ='DELETE_PAYMENT_FAILURE'
export const SET_PAYMENT_STATUS_SUCCESS = 'SET_PAYMENT_STATUS_SUCCESS'
export const SET_PAYMENT_STATUS_FAILURE = 'SET_PAYMENT_STATUS_FAILURE'

export const RETRIEVE_EXPENSES_SUCCESS = 'RETRIEVE_EXPENSES_SUCCESS'
export const RETRIEVE_EXPENSES_FAILURE = 'RETRIEVE_EXPENSES_FAILURE'
export const CREATE_EXPENSE_SUCCESS = 'CREATE_EXPENSE_SUCCESS'
export const CREATE_EXPENSE_FAILURE = 'CREATE_EXPENSE_FAILURE'
export const EDIT_EXPENSE_SUCCESS = 'EDIT_EXPENSE_SUCCESS'
export const EDIT_EXPENSE_FAILURE = 'EDIT_EXPENSE_FAILURE'
export const DELETE_EXPENSE_SUCCESS ='DELETE_EXPENSE_SUCCESS'
export const DELETE_EXPENSE_FAILURE ='DELETE_EXPENSE_FAILURE'

export const LOGIN_SUCCESS ='LOGIN_SUCCESS';
export const LOGIN_FAILURE ='LOGIN_FAILURE';
export const LOGIN_REQUEST ='LOGIN_REQUEST';
export const LOGIN_CHECK_SUCCESS ='LOGIN_CHECK_SUCCESS';
export const LOGIN_CHECK_FAILURE ='LOGIN_CHECK_FAILURE';
export const LOGIN_CHECK_REQUEST ='LOGIN_CHECK_REQUEST';

export const LOGOUT_SUCCESS ='LOGOUT_SUCCESS'

export const RETRIEVE_STOCKS_CATEGORIES_FAILURE = 'RETRIEVE_STOCKS_CATEGORIES_FAILURE';
export const RETRIEVE_STOCKS_CATEGORIES_SUCCESS = 'RETRIEVE_STOCKS_CATEGORIES_SUCCESS';

export const RETRIEVE_SUMMARY_DASHBOARD_REPORT_SUCCESS = 'RETRIEVE_SUMMARY_DASHBOARD_REPORT_SUCCESS';
export const RETRIEVE_SUMMARY_DASHBOARD_REPORT_FAILURE = 'RETRIEVE_SUMMARY_DASHBOARD_REPORT_FAILURE';
export const RETRIEVE_STOCKS_CATEGORIES_REQUEST = 'RETRIEVE_STOCKS_CATEGORIES_REQUEST';

export const RETRIEVE_STOCK_REPORT_SUCCESS = 'RETRIEVE_STOCK_REPORT_SUCCESS'
export const RETRIEVE_STOCK_REPORT_FAILURE = 'RETRIEVE_STOCK_REPORT_FAILURE'

export const RETRIEVE_ACTIVITY_LOG_SUCCESS = 'RETRIEVE_ACTIVITY_LOG_SUCCESS'
export const RETRIEVE_ACTIVITY_LOG_FAILURE = 'RETRIEVE_ACTIVITY_LOG_FAILURE'

export const RETRIEVE_PAYMENT_REPORT_SUCCESS = 'RETRIEVE_PAYMENT_REPORT_SUCCESS'
export const RETRIEVE_PAYMENT_REPORT_FAILURE = 'RETRIEVE_PAYMENT_REPORT_FAILURE'

export const RETRIEVE_PRODUCT_REPORT_SUCCESS = 'RETRIEVE_PRODUCT_REPORT_SUCCESS'
export const RETRIEVE_PRODUCT_REPORT_FAILURE = 'RETRIEVE_PRODUCT_REPORT_FAILURE'

export const FINISH_SALE_SUCCESS ='FINISH_SALE_SUCCESS';
export const FINISH_SALE_FAILURE ='FINISH_SALE_FAILURE';

export const SET_FAVORITE_PRODUCT_SUCCESS ='SET_FAVORITE_PRODUCT_SUCCESS';
export const SET_FAVORITE_PRODUCT_FAILURE ='SET_FAVORITE_PRODUCT_FAILURE';
export const RETRIEVE_STOCK_FOR_ITEM_SUCCESS = 'RETRIEVE_STOCK_FOR_ITEM_SUCCESS';
export const RETRIEVE_STOCK_FOR_ITEM_FAILURE = 'RETRIEVE_STOCK_FOR_ITEM_FAILURE';
export const DELETE_STOCK_FOR_ITEM_SUCCESS = 'DELETE_STOCK_FOR_ITEM_SUCCESS';