import CounterPage from './CounterPage';
import App from './App';
import HomePage from './HomePage';
import Root from './Root';
import NavbarPage from './NavbarPage';
import ProductPage from './ProductPage';
import ClientPage from './ClientPage';
import DealerPage from './DealerPage';
import StockPage from './StockPage';
