import CounterPage from './CounterPage';
import App from './App';
import SalePage from './SalePage';
import Root from './Root';
import NavbarPage from './NavbarPage';
import ProductPage from './ProductPage';
import ClientPage from './ClientPage';
import DealerPage from './DealerPage';
import StockPage from './StockPage';
import ReceivingPage from './ReceivingPage'
import PaymentPage from '.PaymentPage'
import ExpensePage from '.ExpensePage'
